name: GitActions Demo1
on: push
jobs:
  GitActions-demo-job:
    name: Demo Job
    runs-on: ubuntu-latest
    steps:
    - name: Print an environment
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: junhyun
        LAST_NAME: son
        AWS_JOB_NAME: joe.son
      run: |
        echo $MY_VAR $FIRST_NAME $LAST_NAME.
        echo $MY_VAR $AWS_JOB_NAME.
